import {
  cssHandler,
  csvHandler,
  htmHandler,
  htmlHandler,
  jpegHandler,
  jpgHandler,
  jsedocumentHandler,
  jseHandler,
  jsHandler,
  jsonHandler,
  mdHandler,
  mjsHandler,
  oridocumentHandler,
  oriHandler,
  tsHandler,
  txtHandler,
  wasmHandler,
  xhtmlHandler,
  yamlHandler,
  ymlHandler,
} from "../internal.js";

export default {
  "css.handler": cssHandler,
  "csv.handler": csvHandler,
  "htm.handler": htmHandler,
  "html.handler": htmlHandler,
  "jpeg.handler": jpegHandler,
  "jpg.handler": jpgHandler,
  "js.handler": jsHandler,
  "jse.handler": jseHandler,
  "jsedocument.handler": jsedocumentHandler,
  "json.handler": jsonHandler,
  "md.handler": mdHandler,
  "mjs.handler": mjsHandler,
  "ori.handler": oriHandler,
  "oridocument.handler": oridocumentHandler,
  "ts.handler": tsHandler,
  "txt.handler": txtHandler,
  "wasm.handler": wasmHandler,
  "xhtml.handler": xhtmlHandler,
  "yaml.handler": yamlHandler,
  "yml.handler": ymlHandler,
};
