import ExplorableObject from "../../src/core/ExplorableObject.js";
import execute from "../../src/eg/execute.js";
import * as ops from "../../src/eg/ops.js";
import assert from "../assert.js";

describe("execute", () => {
  it("can execute", async () => {
    // Match the array representation of code generated by the parser.
    const code = [
      [ops.scope, "greet"],
      [ops.scope, "name"],
    ];

    const graph = new ExplorableObject({
      async greet(name) {
        return `Hello ${name}`;
      },
      name: "world",
    });
    const result = await execute.call(graph, code);
    assert.equal(result, "Hello world");
  });

  it("can resolve substitutions in a template literal", async () => {
    const graph = new ExplorableObject({
      name: "world",
    });

    const code = [ops.concat, "Hello, ", [ops.scope, "name"], "."];

    const result = await execute.call(graph, code);
    assert.equal(result, "Hello, world.");
  });
});
