import ExplorableObject from "../../src/core/ExplorableObject.js";
import execute from "../../src/language/execute.js";
import * as ops from "../../src/language/ops.js";
import assert from "../assert.js";

describe("execute", () => {
  it("can execute", async () => {
    // Match the array representation of code generated by the parser.
    const code = [
      [ops.scope, "greet"],
      [ops.scope, "name"],
    ];

    const graph = new ExplorableObject({
      async greet(name) {
        return `Hello ${name}`;
      },
      name: "world",
    });
    const result = await execute.call(graph, code);
    assert.equal(result, "Hello world");
  });

  it("can obtain scope from function context", async () => {
    const code = [ops.scope, "message"];
    const context = {};
    context.scope = {
      message: "Hello",
    };
    const result = await execute.call(context, code);
    assert.equal(result, "Hello");
  });
});
